server:
    port: 8081

spring:
    main:
        banner-mode: off
    application:
        name: service-registry

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka
            fetchRegistry: false
            registerWithEureka: false
