services:
    rabbitmq:
        image: rabbitmq:3.12-management
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        container_name: rabbitmq
    service-registry:
        image: service-registry
        build:
            dockerfile: ./Dockerfile
            context: ./service-registry
        ports:
            - 8081:8081
        container_name: service-registry
    estoque-ms:
        image: estoque-ms
        build:
            dockerfile: ./Dockerfile
            context: ./estoque-ms
        environment:
            - SERVICE_REGISTRY_URL=http://service-registry:8081/eureka
            - RABBIT_HOST=rabbitmq
            - RABBIT_USERNAME=admin
            - RABBIT_PASSWORD=admin
        container_name: estoque-ms
        depends_on:
            - rabbitmq
            - service-registry
    gateway:
        image: gateway
        build:
            dockerfile: ./Dockerfile
            context: ./gateway
        ports:
            - 8082:8082
        environment:
            - SERVICE_REGISTRY_URL=http://service-registry:8081/eureka
        container_name: gateway
        depends_on:
            - service-registry
    pedido-api:
        image: pedido-api
        build:
            dockerfile: ./Dockerfile
            context: ./pedido-api
        environment:
            - SERVICE_REGISTRY_URL=http://service-registry:8081/eureka
            - RABBIT_HOST=rabbitmq
            - RABBIT_USERNAME=admin
            - RABBIT_PASSWORD=admin
        container_name: pedido-api
        depends_on:
            - rabbitmq
            - service-registry
            - estoque-ms