server:
    port: 0

spring:
    application:
        name: estoque-ms
    rabbitmq:
        host: localhost
        port: 5672
        username: ${RABBIT_USERNAME:fujikawa}
        password: ${RABBIT_PASSWORD:fujikawa}

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8081/eureka
    instance:
        instanceId: ${spring.application.name}:${random.int}    

app:
    rabbitmq:
        estoqueBaixar:
            exchange: pedido.realizado.ex
            queue: estoque.baixar
            