server:
    port: 0

spring:
    main:
        banner-mode: off
    application:
        name: pedidos-ms
    rabbitmq:
        host: ${RABBIT_HOST:localhost}
        port: 5672
        username: ${RABBIT_USERNAME:fujikawa}
        password: ${RABBIT_PASSWORD:fujikawa}

eureka:
    client:
        serviceUrl:
            defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8081/eureka}
    instance:
        instanceId: ${spring.application.name}:${random.int}    

app:
    rabbitmq:
        pedidoRealizado:
            exchange: pedido.realizado.ex